### ISSUE TITLE
Add "new tags" selection to homepage 

### ISSUE THREAD

**Issue by thekugelmeister** [kamatsuoka/goodtags#32]
In addition to the "classic" and "easy" filters, I propose adding a "new" filter to the new homepage.

**Current functionality**
In my use of the app, I often enjoy perusing the most recent uploads to the database. The current set of steps to accomplish this are as follows:
- go to the search tab
- ensure the search field is blank 
- clear settings for parts and media
- deselect offline search
- hit the search button

This works, but is onerous.

**Proposed functionality**
Upon selecting the "new" button on the homepage, a database request is made that always performs the most permissive request to query for the most recent uploads to the database, regardless of the settings in the search tab, without changing those settings.

**Comment by kamatsuoka** [comment]
@thekugelmeister new tags link added to the homepage in the latest beta

**Comment by thekugelmeister** [comment]
Looks great! Closing.
