### ISSUE TITLE
[bug?] Non-favorited labeled tags

### ISSUE THREAD

**Issue by thekugelmeister** [kamatsuoka/goodtags#6]
In the current version of the app (v2.1.8), it is possible to add labels to non-favorited tags. This may be considered a bug or a feature, which may spark a larger discussion. However, there are seemingly unintended and undesirable consequences of this design as currently implemented.

# How to reproduce

Very straightforward: just add a label to a tag without adding it as a favorite.

# What happens

Upon selecting the label containing that tag from the menu drawer, the app goes to and highlights the Faves tab. It then displays all of the tags in that label, even the ones that are not Faves. As a result, when subsequently deselecting the label, the non-favorited tag counterintuitively disappears from the screen.

# Thoughts/ideas
- If the differentiation between labels and faves is desired, can the Faves tab not be highlighted when viewing labels?
- If the Faves tab is redundant with labels, maybe it could be done away with entirely?
- labeling a tag could automatically mark it as a favorite

**Comment by kamatsuoka** [comment]
Thinking of 
- renaming Faves as "My Tags" that displays labeled tags
- making Favorites a label

**Comment by thekugelmeister** [comment]
Updates to the current version seem to make the distinction between favorites and labels very clear! I'll close this as complete. Thank you!
