### ISSUE TITLE
request headers

### ISSUE THREAD

**Issue by HAdamCode** [kamatsuoka/goodtags#8]
I was wondering if you might be able to include request headers for web if you know them. I am trying to integrate the barbershoptags api into my personal app and am getting errors on web. If you don't know the headers, no worries. But if you do, you can reach me personally at hunter.j.adam@gmail.com. Thank you!

**Comment by kamatsuoka** [comment]
I'm not aware of any specific request headers you'd need for a web app, sorry. You could try reaching out to the admin at barbershoptags.com.
